elasticsearch:
  agent:
    agent-id: HJ
    home-dir: .
    route-dir: ${elasticsearch.agent.home-dir}/routes

spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
    username: GMDMF
    password: gmdmf
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  quartz:
    scheduler-name: HJScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: HJScheduler
            instanceId: HJSchedulerInstance
          threadPool:
            threadCount: 10
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_ 
            useProperties: true
            isClustered : true
            misfireThreshold: 600000

# Apache Camel
camel:
  springboot:
    main-run-controller: true
  component:
    kafka:
      group-id: center
      #brokers: 10.175.91.211:9092,10.175.91.212:9092,10.175.91.213:9092
      brokers:  10.47.39.67:9092,10.47.39.124:9092
# Logging  
logging:
  level:
    kr.go.gmd.eips: INFO
    org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy: TRACE #쿼리 보고 싶을 경우
    org.apache.camel.component.sql.stored: debug
    kr.go.gmd.eips.center.gmdm.provide.monitor.qualify.repository.QualifyRepository: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: error
    org.apache.kafka: warn  